/*
 * autogen_ekf_propagation.c
 *
 * Embedded MATLAB Coder code generation for function 'autogen_ekf_propagation'
 *
 * C source code generated on: Wed Aug 24 16:49:08 2011
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "autogen_ekf_propagation.h"

/* Type Definitions */

/* Named Constants */

/* Variable Declarations */

/* Variable Definitions */

/* Function Declarations */

/* Function Definitions */
void autogen_ekf_propagation(const real32_T eml_in1[20], const real32_T eml_in2
  [3], const real32_T eml_in3[3], real32_T eml_dt,
  real32_T eml_x_new[16])
{
  real32_T eml_t2;
  real32_T eml_t3;
  real32_T eml_t4;
  real32_T eml_t5;
  real32_T eml_t6;
  real32_T eml_t7;
  real32_T eml_t8;
  real32_T eml_t9;
  real32_T eml_t10;
  real32_T eml_t11;
  real32_T eml_t12;
  real32_T eml_t13;
  real32_T eml_t14;
  real32_T eml_t15;

  /* AUTOGEN_EKF_PROPAGATION */
  /*     X_NEW = AUTOGEN_EKF_PROPAGATION(IN1,IN2,IN3,DT) */
  /*     This function was generated by the Symbolic Math Toolbox version 5.5. */
  /*     24-Aug-2011 16:48:53 */
  eml_t2 = eml_in2[1] - eml_in1[14];
  eml_t3 = rt_pow32_snf(eml_in1[6], 2.0F);
  eml_t4 = rt_pow32_snf(eml_in1[7], 2.0F);
  eml_t5 = rt_pow32_snf(eml_in1[8], 2.0F);
  eml_t6 = rt_pow32_snf(eml_in1[9], 2.0F);
  eml_t7 = eml_in2[0] - eml_in1[13];
  eml_t8 = eml_in1[7] * eml_in1[8] * 2.0F;
  eml_t9 = eml_in2[2] - eml_in1[15];
  eml_t10 = eml_in1[6] * eml_in1[8] * 2.0F;
  eml_t11 = eml_in1[7] * eml_in1[9] * 2.0F;
  eml_t12 = eml_in1[6] * eml_in1[7] * 2.0F;
  eml_t13 = eml_in3[0] - eml_in1[10];
  eml_t14 = eml_in3[1] - eml_in1[11];
  eml_t15 = eml_in3[2] - eml_in1[12];
  eml_x_new[0] = eml_in1[0] + eml_dt * eml_in1[3];
  eml_x_new[1] = eml_in1[1] + eml_dt * eml_in1[4];
  eml_x_new[2] = eml_in1[2] + eml_dt * eml_in1[5];
  eml_x_new[3] = eml_in1[3] + eml_dt * ((eml_t9 * (eml_t10 + eml_t11) + eml_t7 *
    (((eml_t3 + eml_t4) - eml_t5) - eml_t6)) + eml_t2
    * (eml_t8 - eml_in1[6] * eml_in1[9] * 2.0F));
  eml_x_new[4] = eml_in1[4] + eml_dt * ((eml_t2 * (((eml_t3 - eml_t4) + eml_t5)
    - eml_t6) - eml_t9 * (eml_t12 - eml_in1[8] *
    eml_in1[9] * 2.0F)) + eml_t7 * (eml_t8 + eml_in1[6] * eml_in1[9] * 2.0F));
  eml_x_new[5] = eml_in1[5] - eml_dt * (((eml_t7 * (eml_t10 - eml_t11) - eml_t9 *
    (((eml_t3 - eml_t4) - eml_t5) + eml_t6)) -
    eml_t2 * (eml_t12 + eml_in1[8] * eml_in1[9] * 2.0F)) + 9.81F);
  eml_x_new[6] = ((eml_in1[6] - eml_dt * eml_t13 * eml_in1[7] * 0.5F) - eml_dt *
                  eml_t14 * eml_in1[8] * 0.5F) - eml_dt * eml_t15
    * eml_in1[9] * 0.5F;
  eml_x_new[7] = ((eml_in1[7] + eml_dt * eml_t13 * eml_in1[6] * 0.5F) - eml_dt *
                  eml_t14 * eml_in1[9] * 0.5F) + eml_dt * eml_t15
    * eml_in1[8] * 0.5F;
  eml_x_new[8] = ((eml_in1[8] + eml_dt * eml_t13 * eml_in1[9] * 0.5F) + eml_dt *
                  eml_t14 * eml_in1[6] * 0.5F) - eml_dt * eml_t15
    * eml_in1[7] * 0.5F;
  eml_x_new[9] = ((eml_in1[9] - eml_dt * eml_t13 * eml_in1[8] * 0.5F) + eml_dt *
                  eml_t14 * eml_in1[7] * 0.5F) + eml_dt * eml_t15
    * eml_in1[6] * 0.5F;
  eml_x_new[10] = eml_in1[10];
  eml_x_new[11] = eml_in1[11];
  eml_x_new[12] = eml_in1[12];
  eml_x_new[13] = eml_in1[13];
  eml_x_new[14] = eml_in1[14];
  eml_x_new[15] = eml_in1[15];
}

/* End of Embedded MATLAB Coder code generation (autogen_ekf_propagation.c) */
