/*
 * autogen_ekf_propagation.c
 *
 * Embedded MATLAB Coder code generation for function 'autogen_ekf_propagation'
 *
 * C source code generated on: Tue Aug 16 17:54:01 2011
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "autogen_ekf_propagation.h"
#include "autogen_mul_quat.h"

/* Type Definitions */

/* Named Constants */

/* Variable Declarations */

/* Variable Definitions */

/* Function Declarations */

/* Function Definitions */
void autogen_ekf_propagation(const real32_T eml_in1[20], const real32_T eml_in2
  [3], const real32_T eml_in3[3], real32_T eml_dt,
  real32_T eml_x_new[16])
{
  real32_T eml_t261;
  real32_T eml_t262;
  real32_T eml_t263;
  real32_T eml_t264;
  real32_T eml_t265;
  real32_T eml_t266;
  real32_T eml_t267;
  real32_T eml_t268;
  real32_T eml_t269;
  real32_T eml_t270;
  real32_T eml_t271;
  real32_T eml_t272;
  real32_T eml_t273;
  real32_T eml_t274;

  /* AUTOGEN_EKF_PROPAGATION */
  /*     X_NEW = AUTOGEN_EKF_PROPAGATION(IN1,IN2,IN3,DT) */
  /*     This function was generated by the Symbolic Math Toolbox version 5.5. */
  /*     16-Aug-2011 17:54:00 */
  eml_t261 = eml_in2[1] - eml_in1[14];
  eml_t262 = rt_pow32_snf(eml_in1[6], 2.0F);
  eml_t263 = rt_pow32_snf(eml_in1[7], 2.0F);
  eml_t264 = rt_pow32_snf(eml_in1[8], 2.0F);
  eml_t265 = rt_pow32_snf(eml_in1[9], 2.0F);
  eml_t266 = eml_in2[0] - eml_in1[13];
  eml_t267 = eml_in1[7] * eml_in1[8] * 2.0F;
  eml_t268 = eml_in2[2] - eml_in1[15];
  eml_t269 = eml_in1[6] * eml_in1[8] * 2.0F;
  eml_t270 = eml_in1[7] * eml_in1[9] * 2.0F;
  eml_t271 = eml_in1[6] * eml_in1[7] * 2.0F;
  eml_t272 = eml_in3[0] - eml_in1[10];
  eml_t273 = eml_in3[1] - eml_in1[11];
  eml_t274 = eml_in3[2] - eml_in1[12];
  eml_x_new[0] = eml_in1[0] + eml_dt * eml_in1[3];
  eml_x_new[1] = eml_in1[1] + eml_dt * eml_in1[4];
  eml_x_new[2] = eml_in1[2] + eml_dt * eml_in1[5];
  eml_x_new[3] = eml_in1[3] + eml_dt * ((eml_t268 * (eml_t269 + eml_t270) +
    eml_t266 * (((eml_t262 + eml_t263) - eml_t264) -
                eml_t265)) + eml_t261 * (eml_t267 - eml_in1[6] * eml_in1[9] *
    2.0F));
  eml_x_new[4] = eml_in1[4] + eml_dt * ((eml_t261 * (((eml_t262 - eml_t263) +
    eml_t264) - eml_t265) + eml_t266 * (eml_t267 +
    eml_in1[6] * eml_in1[9] * 2.0F)) - eml_t268 * (eml_t271 - eml_in1[8] *
    eml_in1[9] * 2.0F));
  eml_x_new[5] = eml_in1[5] - eml_dt * (((eml_t266 * (eml_t269 - eml_t270) -
    eml_t268 * (((eml_t262 - eml_t263) - eml_t264) +
                eml_t265)) - eml_t261 * (eml_t271 + eml_in1[8] * eml_in1[9] *
    2.0F)) + 9.81F);
  eml_x_new[6] = ((eml_in1[6] - eml_dt * eml_t272 * eml_in1[7] * 0.5F) - eml_dt *
                  eml_t273 * eml_in1[8] * 0.5F) - eml_dt *
    eml_t274 * eml_in1[9] * 0.5F;
  eml_x_new[7] = ((eml_in1[7] + eml_dt * eml_t272 * eml_in1[6] * 0.5F) + eml_dt *
                  eml_t274 * eml_in1[8] * 0.5F) - eml_dt *
    eml_t273 * eml_in1[9] * 0.5F;
  eml_x_new[8] = ((eml_in1[8] + eml_dt * eml_t273 * eml_in1[6] * 0.5F) - eml_dt *
                  eml_t274 * eml_in1[7] * 0.5F) + eml_dt *
    eml_t272 * eml_in1[9] * 0.5F;
  eml_x_new[9] = ((eml_in1[9] - eml_dt * eml_t272 * eml_in1[8] * 0.5F) + eml_dt *
                  eml_t273 * eml_in1[7] * 0.5F) + eml_dt *
    eml_t274 * eml_in1[6] * 0.5F;
  eml_x_new[10] = eml_in1[10];
  eml_x_new[11] = eml_in1[11];
  eml_x_new[12] = eml_in1[12];
  eml_x_new[13] = eml_in1[13];
  eml_x_new[14] = eml_in1[14];
  eml_x_new[15] = eml_in1[15];
}

/* End of Embedded MATLAB Coder code generation (autogen_ekf_propagation.c) */
