int32      camera_pitch         # desired camera pitch angle (deg)
int32      camera_roll	        # desired camera roll angle  (deg)
---
bool	   result		# true if successfully sent the command to HLP
